;; SPDX-FileCopyrightText: 2018 D. Guthrie <dguthrie@posteo.net>
;;;
;;; SPDX-License-Identifier: MIT
#!r6rs

(import (only (chezscheme) include)
        (rename (rnrs (6)) (exact? r6rs:exact?) (inexact? r6rs:inexact?))
        (only (srfi :1 lists) list= take drop count take-while drop-while list-index)
        (rename (srfi :1 lists) (remove remove/?))
        (srfi :64 testing)
        (only (srfi :152 strings) string-segment)
        (only (srfi :158 generators-and-accumulators) circular-generator gfilter gmap)
        (only (srfi :194 random-data-generators)
              make-random-integer-generator
              make-random-char-generator
              make-random-real-generator
              make-random-rectangular-generator)
        (only (srfi :235 combinators) flip)
        (only (srfi :252 property-testing)
              list-generator-of
              symbol-generator)
        (srfi :160 base)
	(srfi :160 u8) (srfi :160 u16) (srfi :160 u32) (srfi :160 u64)
	(srfi :160 s8) (srfi :160 s16) (srfi :160 s32) (srfi :160 s64)
	(srfi :160 f32) (srfi :160 f64)
        (srfi :160 c64) (srfi :160 c128)
        (except (srfi :160 meta utils) exact? inexact?)
        (srfi :160 meta curried)
        (srfi :160 test aux))

(include "test/srfi-160-base-properties.scm")

(include "test/srfi-160-mutators-properties.scm")
(include "test/srfi-160-constructors-properties.scm")
(include "test/srfi-160-iteration-properties.scm")
(include "test/srfi-160-searching-properties.scm")

(include "test/srfi-160-mutators-tests.scm")
(include "test/srfi-160-constructors-tests.scm")
(include "test/srfi-160-iteration-tests.scm")
(include "test/srfi-160-searching-tests.scm")

(run-s8vector-mutators-tests)
(run-s16vector-mutators-tests)
(run-s32vector-mutators-tests)
(run-s64vector-mutators-tests)
(run-u8vector-mutators-tests)
(run-u16vector-mutators-tests)
(run-u32vector-mutators-tests)
(run-u64vector-mutators-tests)
(run-f32vector-mutators-tests)
(run-f64vector-mutators-tests)
(run-c64vector-mutators-tests)
(run-c128vector-mutators-tests)

(run-s8vector-constructors-tests)
(run-s16vector-constructors-tests)
(run-s32vector-constructors-tests)
(run-s64vector-constructors-tests)
(run-u8vector-constructors-tests)
(run-u16vector-constructors-tests)
(run-u32vector-constructors-tests)
(run-u64vector-constructors-tests)
(run-f32vector-constructors-tests)
(run-f64vector-constructors-tests)
(run-c64vector-constructors-tests)
(run-c128vector-constructors-tests)

(run-s8vector-iteration-tests)
(run-s16vector-iteration-tests)
(run-s32vector-iteration-tests)
(run-s64vector-iteration-tests)
(run-u8vector-iteration-tests)
(run-u16vector-iteration-tests)
(run-u32vector-iteration-tests)
(run-u64vector-iteration-tests)
(run-f32vector-iteration-tests)
(run-f64vector-iteration-tests)
(run-c64vector-iteration-tests)
(run-c128vector-iteration-tests)

(run-s8vector-searching-tests)
(run-s16vector-searching-tests)
(run-s32vector-searching-tests)
(run-s64vector-searching-tests)
(run-u8vector-searching-tests)
(run-u16vector-searching-tests)
(run-u32vector-searching-tests)
(run-u64vector-searching-tests)
(run-f32vector-searching-tests)
(run-f64vector-searching-tests)
(run-c64vector-searching-tests)
(run-c128vector-searching-tests)
