;;;; srfi-132.import.scm - GENERATED BY CHICKEN 4.10.0 -*- Scheme -*-

(eval '(import scheme (only chicken include error)))
(##sys#register-compiled-module
  'srfi-132
  (list)
  '((list-sorted? . srfi-132#list-sorted?)
    (vector-sorted? . srfi-132#vector-sorted?)
    (list-merge . srfi-132#list-merge)
    (vector-merge . srfi-132#vector-merge)
    (list-sort . srfi-132#list-sort)
    (vector-sort . srfi-132#vector-sort)
    (list-stable-sort . srfi-132#list-stable-sort)
    (vector-stable-sort . srfi-132#vector-stable-sort)
    (list-merge! . srfi-132#list-merge!)
    (vector-merge! . srfi-132#vector-merge!)
    (list-sort! . srfi-132#list-sort!)
    (vector-sort! . srfi-132#vector-sort!)
    (list-stable-sort! . srfi-132#list-stable-sort!)
    (vector-stable-sort! . srfi-132#vector-stable-sort!)
    (list-delete-neighbor-dups . srfi-132#list-delete-neighbor-dups)
    (vector-delete-neighbor-dups . srfi-132#vector-delete-neighbor-dups)
    (list-delete-neighbor-dups! . srfi-132#list-delete-neighbor-dups!)
    (vector-delete-neighbor-dups! . srfi-132#vector-delete-neighbor-dups!))
  (list)
  (list))

;; END OF FILE
